export const android_versions = [
  "Android 1.0 Astro",
  "Android 1.0 Bender",
  "Android 1.1 Petit Four",
  "Android 1.5 Cupcake",
  "Android 1.6 Donut",
  "Android 2.0 Eclair",
  "Android 2.0.1 Eclair_MR1",
  "Android 2.1 Eclair_MR2",
  "Android 2.2 Froyo",
  "Android 2.3 Gingerbread",
  "Android 2.3.3 Gingerbread_MR1",
  "Android 3.0 Honeycomb",
  "Android 3.1 Honeycomb_MR1",
  "Android 3.2 Honeycomb_MR2",
  "Android 4.0 Ice Cream Sandwich",
  "Android 4.0.3 Ice Cream Sandwich_MR1",
  "Android 4.1 Jelly Bean",
  "Android 4.2 Jelly Bean_MR1",
  "Android 4.3 Jelly Bean_MR2",
  "Android 4.4 KitKat",
  "Android 4.4W KitKat Wear",
  "Android 5.0 Lollipop",
  "Android 5.1 Lollipop",
  "Android 6.0 Marshmallow",
  "Android 7.0 Nougat",
  "Android 7.1 Nougat",
  "Android 8.0 Oreo",
  "Android 8.1 Oreo",
  "Android 9 Pie",
  "Android 10 Q",
  "Android 11 R",
  "Android 12 S",
  "Android 13 T",
  "Android 14 U",
  "Android 15 V",
  "Android 16 W",
  "Android 17 X",
  "Android 18 Y",
];
