// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2024/8/20 08:54:35
const configMerger = require("/Users/oboard/Development/fraud-terminator-projects/Fraud/node_modules/.pnpm/@nuxtjs+tailwindcss@6.12.1_magicast@0.3.4_rollup@4.21.0/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["/Users/oboard/Development/fraud-terminator-projects/Fraud/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/oboard/Development/fraud-terminator-projects/Fraud/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/oboard/Development/fraud-terminator-projects/Fraud/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/oboard/Development/fraud-terminator-projects/Fraud/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/oboard/Development/fraud-terminator-projects/Fraud/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/oboard/Development/fraud-terminator-projects/Fraud/plugins/**/*.{js,ts,mjs}","/Users/oboard/Development/fraud-terminator-projects/Fraud/composables/**/*.{js,ts,mjs}","/Users/oboard/Development/fraud-terminator-projects/Fraud/utils/**/*.{js,ts,mjs}","/Users/oboard/Development/fraud-terminator-projects/Fraud/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/oboard/Development/fraud-terminator-projects/Fraud/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/oboard/Development/fraud-terminator-projects/Fraud/app.config.{js,ts,mjs}"] }));

module.exports = config
